<a href="https://colab.research.google.com/github/rohitjaiswalrj32/Python-Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Importing Numpy Library

import numpy as np

#Example:
import numpy as np

# Create a simple array
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


In [5]:
# Diffrence Between List and Numpy Array:

# | Feature                | Python List                 | NumPy Array                                 |
# | ---------------------- | --------------------------- | ------------------------------------------- |
# |   Data Type            | Can store mixed data types  | Homogeneous (same data type)                |
# |   Performance          | Slower for large operations | Much faster (uses C under the hood)         |
# |   Functionality        | Limited built-in operations | Rich mathematical functions                 |
# |   Memory Consumption   | More                        | Less (compact, fixed type)                  |
# |   Broadcasting         | Not supported               | Supported (auto operations on all elements) |


In [7]:
#1. Creating a List vs NumPy Array

# Python List
py_list = [1, 2, 3, 4]
print(py_list)

# NumPy Array
import numpy as np
np_array = np.array([1, 2, 3, 4])
print(np_array)

[1, 2, 3, 4]
[1 2 3 4]


In [9]:
#2. Element-wise Addition

# Python List
py_result = [x + 2 for x in py_list]
print("Python List:", py_result)

# NumPy Array
np_result = np_array + 2
print("NumPy Array:", np_result)


Python List: [3, 4, 5, 6]
NumPy Array: [3 4 5 6]


In [14]:
#3. Performance Test

import time

# Large list
py_list = list(range(1000000))
np_array = np.array(py_list)

# Time taken by Python list
start = time.time()
py_result = [x * 2 for x in py_list]
print("List Time:", time.time() - start)

# Time taken by NumPy
start = time.time()
np_result = np_array * 2
print("NumPy Time:", time.time() - start)


# Note:

# NumPy arrays are faster, more memory-efficient, and provide advanced math capabilities.
# For data analysis, NumPy arrays are preferred over Python lists.

List Time: 0.05240464210510254
NumPy Time: 0.003787994384765625


In [15]:
#NumPy Array Creation Techniques

#1. Creating from a Python List or Tuple

import numpy as np

# From list
arr1 = np.array([1, 2, 3, 4])
print("From list:", arr1)

# From tuple
arr2 = np.array((5, 6, 7, 8))
print("From tuple:", arr2)

From list: [1 2 3 4]
From tuple: [5 6 7 8]


In [16]:
#2. Creating Arrays of Zeros, Ones, or a Specific Value

# Array of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# Array of ones
ones = np.ones((3, 3))
print("Ones:\n", ones)

# Array filled with a specific value
full = np.full((2, 4), 7)
print("Full:\n", full)

Zeros: [0. 0. 0. 0. 0.]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7 7 7]
 [7 7 7 7]]


In [17]:
# Similar to Python's range()

arr_range = np.arange(0, 10, 2)  # start=0, stop=10, step=2
print("Arange:", arr_range)


Arange: [0 2 4 6 8]


In [18]:
#4. Creating Arrays with Linearly Spaced Values

# 5 numbers evenly spaced between 0 and 1
arr_linspace = np.linspace(0, 1, 5)
print("Linspace:", arr_linspace)

Linspace: [0.   0.25 0.5  0.75 1.  ]


In [20]:
#5. Creating Identity Matrices

identity = np.eye(4)
print("Identity Matrix:\n", identity)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
#6. Creating Random Arrays

# Random floats between 0 and 1 (3x3)
rand_float = np.random.rand(3, 3)
print("Random Float Array:\n", rand_float)

# Random integers between 0 and 10 (5 elements)
rand_int = np.random.randint(0, 10, 5)
print("Random Int Array:", rand_int)

Random Float Array:
 [[0.18591125 0.89189206 0.81523071]
 [0.69115558 0.55963777 0.90791623]
 [0.59113133 0.45833362 0.72425332]]
Random Int Array: [8 5 6 4 5]


In [31]:
# Practice Exercise:

# Q1. An array of ten zeros
zero_array = np.zeros(10)
print("Array of Zeros:", zero_array)

# Q2. A 2x5 array filled with the number 9
array_of_9 = np.full((2,5), 9)
print("Array of 9s:\n", array_of_9)

# Q3. A range array from 10 to 50 with step size 5
range_array = np.arange(10, 51, 5)
print("Range Array:", range_array)

# Q4. An identity matrix of size 3
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# Q5. A 4x4 random float array
random_float = np.random.rand(4, 4)
print("Random floating Array: \n", random_float)

Array of Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 9s:
 [[9 9 9 9 9]
 [9 9 9 9 9]]
Range Array: [10 15 20 25 30 35 40 45 50]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random floating Array: 
 [[0.5867816  0.29525158 0.09468497 0.85276003]
 [0.02527935 0.05153823 0.34823763 0.89132016]
 [0.96481167 0.8717455  0.03964411 0.97799263]
 [0.19430486 0.7463116  0.43448429 0.57075149]]
