<a href="https://colab.research.google.com/github/rohitjaiswalrj32/Python_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Importing Numpy Library

import numpy as np

#Example:

# Create a simple array
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


In [ ]:
# Diffrence Between List and Numpy Array:

# | Feature                | Python List                 | NumPy Array                                 |
# | ---------------------- | --------------------------- | ------------------------------------------- |
# |   Data Type            | Can store mixed data types  | Homogeneous (same data type)                |
# |   Performance          | Slower for large operations | Much faster (uses C under the hood)         |
# |   Functionality        | Limited built-in operations | Rich mathematical functions                 |
# |   Memory Consumption   | More                        | Less (compact, fixed type)                  |
# |   Broadcasting         | Not supported               | Supported (auto operations on all elements) |


In [ ]:
#1. Creating a List vs NumPy Array

# Python List
py_list = [1, 2, 3, 4]
print(py_list)

# NumPy Array
array1 = np.array([1, 2, 3, 4])
print(array1)

[1, 2, 3, 4]
[1 2 3 4]


In [ ]:
#2. Element-wise Addition

# Python List
py_result = [x + 2 for x in py_list]
print("Python List:", py_result)

# NumPy Array
np_result = np_array + 2
print("NumPy Array:", np_result)


Python List: [3, 4, 5, 6]
NumPy Array: [3 4 5 6]


In [ ]:
#3. Performance Test

import time

# Large list
py_list = list(range(1000000))
np_array = np.array(py_list)

# Time taken by Python list
start = time.time()
py_result = [x * 2 for x in py_list]
print("List Time:", time.time() - start)

# Time taken by NumPy
start = time.time()
np_result = np_array * 2
print("NumPy Time:", time.time() - start)


# Note:

# NumPy arrays are faster, more memory-efficient, and provide advanced math capabilities.
# For data analysis, NumPy arrays are preferred over Python lists.

List Time: 0.05240464210510254
NumPy Time: 0.003787994384765625


In [ ]:
#NumPy Array Creation Techniques

#1. Creating from a Python List or Tuple

# From list
arr1 = np.array([1, 2, 3, 4])
print("From list:", arr1)

# From tuple
arr2 = np.array((5, 6, 7, 8))
print("From tuple:", arr2)

From list: [1 2 3 4]
From tuple: [5 6 7 8]


In [ ]:
#2. Creating Arrays of Zeros, Ones, or a Specific Value

# Array of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# Array of ones
ones = np.ones((3, 3))
print("Ones:\n", ones)

# Array filled with a specific value
full = np.full((2, 4), 7)
print("Full:\n", full)

Zeros: [0. 0. 0. 0. 0.]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7 7 7]
 [7 7 7 7]]


In [ ]:
#3. Similar to Python's range()

arr_range = np.arange(0, 11, 2)  # start=0, stop=11, step=2
print("Arange:", arr_range)


Arange: [ 0  2  4  6  8 10]


In [ ]:
#4. Creating Arrays with Linearly Spaced Values


#Numbers evenly spaced between 0 and 1
arr_linspace = np.linspace(0, 1, 5)
print("Linspace:", arr_linspace)

Linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#5. Creating Identity Matrices

identity = np.eye(4)
print("Identity Matrix:\n", identity)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#6. Creating Random Arrays

# Random floats between 0 and 1
rand_float = np.random.rand(3, 3)
print("Random Float Array:\n", rand_float)

# Random integers between 0 and 10
rand_int = np.random.randint(0, 10, 5)
print("Random Int Array:", rand_int)

Random Float Array:
 [[0.18591125 0.89189206 0.81523071]
 [0.69115558 0.55963777 0.90791623]
 [0.59113133 0.45833362 0.72425332]]
Random Int Array: [8 5 6 4 5]


In [ ]:
# Practice Exercise:

# Q1. An array of ten zeros
zero_array = np.zeros(10)
print("Array of Zeros:", zero_array)

# Q2. A 2x5 array filled with the number 9
array_of_9 = np.full((2,5), 9)
print("Array of 9s:\n", array_of_9)

# Q3. A range array from 10 to 50 with step size 5
range_array = np.arange(10, 51, 5)
print("Range Array:", range_array)

# Q4. An identity matrix of size 3
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# Q5. A 4x4 random float array
random_float = np.random.rand(4, 4)
print("Random floating Array: \n", random_float)

Array of Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 9s:
 [[9 9 9 9 9]
 [9 9 9 9 9]]
Range Array: [10 15 20 25 30 35 40 45 50]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random floating Array: 
 [[0.5867816  0.29525158 0.09468497 0.85276003]
 [0.02527935 0.05153823 0.34823763 0.89132016]
 [0.96481167 0.8717455  0.03964411 0.97799263]
 [0.19430486 0.7463116  0.43448429 0.57075149]]


In [ ]:
#NumPy Array Attributes & Properties:#Every NumPy array has several useful attributes
                                     #that tell you about its structure and data type.

#1. shape: Returns a tuple of the array dimensions.

arr = np.array([[1,2,3], [4,5,6]])
print("Array Shape is:", arr.shape)
print(arr)


#2. size: Total number of elements in the array.

arr = np.array([[1,2,3],
               [4,5,6]])
print("Array Size is:", arr.size)
print(arr)


#3. ndim: Number of array dimensions (axes).
arr = np.array([[
                 [1,2,3],
                 [4,5,6],
                 [7,8,9]
              ]])
print("Array Dimension is:", arr.ndim)
print(arr)


#4. dtype: Data type of elements in the array.
arr = np.array([[["Rohit", "Pratik", "Sagar"],
                 [1,2,3],
                 [1.23, 2.34, 3.45]]])
print("Array Data Type is:", arr.dtype)
print(arr)

#5. itemsize: Size (in bytes) of each element.
print("Item Size is:", arr.itemsize)

#6. data: This shows memory location, usually less used directly.
print("Memory Location is:", arr.data)


Array Shape is: (2, 3)
[[1 2 3]
 [4 5 6]]
Array Size is: 6
[[1 2 3]
 [4 5 6]]
Array Dimension is: 3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Array Data Type is: <U32
[[['Rohit' 'Pratik' 'Sagar']
  ['1' '2' '3']
  ['1.23' '2.34' '3.45']]]
Item Size is: 128
Memory Location is: <memory at 0x7897950a96c0>


In [ ]:
#Practice Exercise:

# Q1. Create arrays of different shapes and data types, then print and interpret their attributes.
array1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Array Shape is:", array1.shape)
print("Array Size is:", array1.size)
print("Array Dimension is:", array1.ndim)
print("Array Datatype is:", array1.dtype)
print("Array Item Size is:", array1.itemsize)
print("Array Location is:", array1.data)
print("\n")


# Q2. Try changing the dtype when creating an array, e.g., np.array([1, 2, 3], dtype=float) and check the difference.
array2 = np.array([1, 2, 3], dtype=float)
print("Array Datatype is:", array2.dtype)
print("\n")

# Q3. Create a 3x2x2 array and print all its attributes
array3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(array3)
print("Shape:", array3.shape)
print("Size:", array3.size)
print("Dimensions:", array3.ndim)
print("Datatype:", array3.dtype)
print("Item Size (bytes):", array3.itemsize)
print("\n")

# Q4. Create a float array: [5.5, 6.6, 7.7]
array_float = np.array([5.5, 6.6, 7.7])
print("Float Array:", array_float)
print("\n")

# Q5. Print shape, size, dimensions, dtype, and itemsize
print("Array Shape:", array3.shape)
print("Array Size:", array3.size)
print("Array Dimension:", array3.ndim)
print("Array Data Type:", array3.dtype)
print("Array Item Size:", array3.itemsize)
print("\n")

# Q6. Create two arrays: one with int, one with float
array_int = np.array([1, 2, 3])
array_float = np.array([1.1, 2.2, 3.3])
print("Integer Array:", array_int)
print("Float Array:", array_float)
print("\n")

# Q7. Compare itemsize and dtype
print("Integer Array Item Size:", array_int.itemsize)
print("Float Array :", array_float.itemsize)
print("\n")
# Q8. Create an array of integers with dtype='int32'
array_int32 = np.array([1, 2, 3], dtype='int32')
print("Integer Array with dtype='int32':", array_int32)
print("\n")

# Q9. Print array and its itemsize
print(array3, "Item Size: ", array3.itemsize)
print("\n")

# Q10. Create a 1D array of 9 elements
array_1d = np.arange(9)
print("1D Array:", array_1d)
print("Size:", array_1d.size)
print("\n")

# Q11. Reshape to 3x3 and print shape, ndim, size
array_3x3 = array_1d.reshape(3, 3)
print("Reshaped 3x3 Array:\n", array_3x3)
print("Shape:", array_3x3.shape)
print("Dimensions:", array_3x3.ndim)


Array Shape is: (2, 5)
Array Size is: 10
Array Dimension is: 2
Array Datatype is: int64
Array Item Size is: 8
Array Location is: <memory at 0x7897967ccd40>


Array Datatype is: float64


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Shape: (1, 3, 3)
Size: 9
Dimensions: 3
Datatype: int64
Item Size (bytes): 8


Float Array: [5.5 6.6 7.7]


Array Shape: (1, 3, 3)
Array Size: 9
Array Dimension: 3
Array Data Type: int64
Array Item Size: 8


Integer Array: [1 2 3]
Float Array: [1.1 2.2 3.3]


Integer Array Item Size: 8
Float Array : 8


Integer Array with dtype='int32': [1 2 3]


[[[1 2 3]
  [4 5 6]
  [7 8 9]]] Item Size:  8


1D Array: [0 1 2 3 4 5 6 7 8]
Size: 9


Reshaped 3x3 Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape: (3, 3)
Dimensions: 2


In [ ]:
# Array Indexing and Slicing: Indexing and slicing in NumPy is similar to Python lists
                              #but offers more powerful and multi-dimensional capabilities.


#Indexing:Indexing helps you access specific elements in arrays.

#1. 1D Indexing: Accessing elements by index
arr = np.array([10, 20, 30, 40])
print("Original 1D Array:", arr)
print("Indexing [0]:", arr[0])
print("Indexing [-1]:", arr[-1])
print("\n")


#2. 2D Indexing: Access elements in rows and columns
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original 2D Array:", arr)
print("Indexing [0,1]:", arr[0, 1])
print("Indexing [0,1]:", arr[1][2])
print("\n")


#Slicing: Just like Python lists, NumPy supports slicing with [start:stop:step].

#1. Slicing 1D Arrays
arr = np.array([10, 20, 30, 40, 50])
print("Original 1D Array:", arr)
print("SLicing [1:4]:", arr[1:4])
print("SLicing [:3]:", arr[:3])
print("SLicing [::2]:", arr[::2])
print("\n")


#2. Slicing 2D Arrays
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original 2D Array:", arr)
print("Slicing [0:2, 1:]:", arr[0:2, 1:])
print("\n")


#Reshaping Arrays: The reshape() function lets you change the shape (rows × columns) of an existing array without changing its data.
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print("Reshaped Array:", reshaped)
print("\n")

#Note: The total number of elements must remain the same.


#Flattening Arrays: The flatten() method converts a multidimensional array into a 1D array.
arr = np.array([[1, 2], [3, 4]])
print("Original Array:", arr)
flat = arr.flatten()
print("Flatten Array:", flat)

Original 1D Array: [10 20 30 40]
Indexing [0]: 10
Indexing [-1]: 40


Original 2D Array: [[1 2 3]
 [4 5 6]]
Indexing [0,1]: 2
Indexing [0,1]: 6


Original 1D Array: [10 20 30 40 50]
SLicing [1:4]: [20 30 40]
SLicing [:3]: [10 20 30]
SLicing [::2]: [10 30 50]


Original 2D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing [0:2, 1:]: [[2 3]
 [5 6]]


Reshaped Array: [[1 2 3]
 [4 5 6]]


Original Array: [[1 2]
 [3 4]]
Flatten Array: [1 2 3 4]


In [ ]:
#Practice Exercise:

# Q1. Create a 1D array of numbers from 0 to 9 and:

# -Print first 5 elements
# -Print last 3 elements
# -Print every second element

arr = np.arange(10)
print("Original Array:", arr)
print("First 5:", arr[:5])
print("Last 3:", arr[-3:])
print("Every 2nd:", arr[::2])
print("\n")

# Q2. Create a 2D array:

# [[10, 20, 30],
#  [40, 50, 60],
#  [70, 80, 90]]

# -Access element 50 using indexing
# -Slice second and third columns
# -Slice first two rows
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
print("Original Array:", arr2d)
print("Accessing element at [1,1]:", arr2d[1, 1])
print("Second & Third Columns:\n", arr2d[:, 1:])
print("First Two Rows:\n", arr2d[:2, :])
print("\n")


# Q3. Create a 3x3 array and:

# -Print the diagonal elements
# -Print the reverse of the second row
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("Diagonal:", np.diag(arr3))
print("Reversed 2nd row:", arr3[1, ::-1])
print("\n")

# Q4. Create a 1D array of 16 elements and reshape it into a 4x4 matrix.
arr = np.arange(16)
print("Original 1D Array:", arr)
reshaped = arr.reshape(4, 4)
print("Reshaped Array:", reshaped)
print("\n")

# Q5. Create a 3x3 matrix and flatten it into a 1D array.
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Original Array:", arr)
flat = arr.flatten()
print("Flatten Array:", flat)
print("\n")

# Q6. Create a 1D array of 12 elements and reshape it into 2 blocks of 3×2 arrays (i.e., shape = (2, 3, 2))
arr = np.arange(12)
print("Original Array:", arr)
reshaped = arr.reshape(2, 3, 2)
print("Reshaped Array:", reshaped)
print("\n")

# Q7. Use ravel() to flatten an array and demonstrate that it returns a view.
arr = np.array([[10, 20], [30, 40]])
ravelled = arr.ravel()
print("Original:", arr)
print("Ravelled:", ravelled)
print("\n")
arr[0, 0] = 99
print("After modifying original:")
print("Original:", arr)
print("Ravelled:", ravelled)
print("\n")

# Q8. Reshape a 1D array of 9 elements using reshape(-1, 3) and explain the result.
arr = np.arange(9)
reshaped = arr.reshape(-1, 3)
print("Original:", arr)
print("Reshaped (-1, 3):", reshaped)


Original Array: [0 1 2 3 4 5 6 7 8 9]
First 5: [0 1 2 3 4]
Last 3: [7 8 9]
Every 2nd: [0 2 4 6 8]


Original Array: [[10 20 30]
 [40 50 60]
 [70 80 90]]
Accessing element at [1,1]: 50
Second & Third Columns:
 [[20 30]
 [50 60]
 [80 90]]
First Two Rows:
 [[10 20 30]
 [40 50 60]]


Diagonal: [1 5 9]
Reversed 2nd row: [6 5 4]


Original 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Original Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flatten Array: [1 2 3 4 5 6 7 8 9]


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


Original: [[10 20]
 [30 40]]
Ravelled: [10 20 30 40]


After modifying original:
Original: [[99 20]
 [30 40]]
Ravelled: [99 20 30 40]


Original: [0 1 2 3 4 5 6 7 8]
Reshaped (-1, 3): [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Array Operations in NumPy: NumPy allows vectorized operations on arrays,
                            #which means you can perform operations on entire arrays without writing loops.
                            #This makes your code cleaner, faster, and more efficient.


##Types of Operations:


#1. Arithmetic Operations

# Addition (+)
# Subtraction (-)
# Multiplication (*)
# Division (/)
# Exponentiation (**)


#2. Comparison Operations

# Greater than (>)
# Less than (<)
# Equal to (==)
# Not equal (!=)


#3. Broadcasting: Performing operations between arrays of different shapes intelligently.

#Example: adding a scalar to an array, or row-wise/column-wise operations.


#4. Aggregate Functions (Universal Functions): sum(), mean(), max(), min(), std(), etc



#Example:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Arithmetic
print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 ** 2)

# Comparison
print(arr1 > 2)
print(arr1 == arr2)

# Broadcasting
print(arr1 + 5)

# Aggregate
matrix = np.array([[1, 2], [3, 4]])
print(np.sum(matrix))
print(np.sum(matrix, axis=0))
print(np.mean(matrix))

[5 7 9]
[ 4 10 18]
[1 4 9]
[False False  True]
[False False False]
[6 7 8]
10
[4 6]
2.5


In [ ]:
#Practice Exercises

# Exercise 1:

# Create two 1D arrays: [10, 20, 30] and [1, 2, 3]
# Perform element-wise addition, subtraction, and multiplication.
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
print("Array1:", arr1, "and its Dimension:", arr1.ndim)
print("Array2:", arr2, "and its Dimension:", arr2.ndim)
addition = arr1+arr2
subtraction = arr1-arr2
multiplication = arr1*arr2
print("Addition:", addition)
print("Subtraction:", subtraction)
print("multiplication:", multiplication)
print("\n")


# Exercise 2:

# Create an array:arr = np.array([[5, 10], [15, 20]])
# Multiply each element by 2 using broadcasting
# Find the mean, max, and standard deviation
arr = np.array([[5,10], [15,20]])
print("Array:", arr)
print("Multiply Elements by 2:", arr * 2)
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))
print("\n")


# Exercise 3:

# Given arr = np.array([100, 200, 300, 400])
# Check which elements are greater than 250
# Add 50 to all elements using broadcasting
arr = np.array([100, 200, 300, 400])
print("Array:", arr)
print("Element Greater than 250:", arr > 250)
print("Add 50 all elements:", arr + 50)

Array1: [10 20 30] and its Dimension: 1
Array2: [1 2 3] and its Dimension: 1
Addition: [11 22 33]
Subtraction: [ 9 18 27]
multiplication: [10 40 90]


Array: [[ 5 10]
 [15 20]]
Multiply Elements by 2: [[10 20]
 [30 40]]
Mean: 12.5
Max: 20
Standard Deviation: 5.5901699437494745


Array: [100 200 300 400]
Element Greater than 250: [False False  True  True]
Add 50 all elements: [150 250 350 450]


In [ ]:
#Boolean Indexing: It allows you to filter elements in an array using boolean conditions.
                   #Instead of using specific indices, you use a condition to get True or False values,
                   #and NumPy returns the elements where the condition is True.


#Example 1: Simple Condition on 1D Array
arr = np.array([10, 20, 30, 40, 50])
condition = arr > 25
print("Boolean Mask:", condition)

filtered = arr[condition]
print("Filtered Elements:", filtered)


#Example 2: Direct Filtering in One Line
arr = np.array([5, 15, 25, 35, 45])
print("Values Greater than 20:", arr[arr > 20])


#Example 3: Boolean Indexing with 2D Arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Elements Greater than 5:", matrix[matrix > 5])


# Example 4: Combine Conditions

# Use logical operators like:

# & → AND
# | → OR
# ~ → NOT

arr = np.array([10, 20, 30, 40, 50])
print("Between 15 and 45:", arr[(arr > 15) & (arr < 45)])
print("Not Equal to 20 or 40:", arr[(arr == 20) | (arr == 40)])
print("Not Greater than 30:", arr[~(arr > 30)])


#Note:
# Must use () around conditions due to Python’s operator precedence.
# Boolean indexing does not modify the original array.
# Can be used for filtering rows/columns, cleaning data, or masking values in data analytics.

Boolean Mask: [False False  True  True  True]
Filtered Elements: [30 40 50]
Values Greater than 20: [25 35 45]
Elements Greater than 5: [6 7 8 9]
Between 15 and 45: [20 30 40]
Not Equal to 20 or 40: [20 40]
Not Greater than 30: [10 20 30]


In [ ]:
# Practice Exercise:

# Q1. Given the array:
#     arr = np.array([5, 10, 15, 20, 25, 30])

# Print all elements greater than 18
# Print all even numbers
# Print elements between 10 and 25 (inclusive)
arr = np.array([5, 10, 15, 20, 25, 30])
print("Original Array:", arr)
print("Elements Greater than 18:", arr[(arr > 18)])
print("Even Elements:", arr[(arr % 2 == 0)])
print("Elements Between 10 and 25:", arr[(arr >= 10) & (arr <= 25)])
print("\n")


# Q2. Given the 2D array:
#     matrix = np.array([[1, 12, 7],
#                        [15, 3, 8],
#                        [9, 20, 5]])

# Print all elements greater than 10
# Print elements that are either less than 5 or greater than 15
# Replace all elements less than 10 with 0 (use boolean indexing)
matrix = np.array([[1, 12, 7], [15, 3, 8], [9, 20, 5]])
print("Original Matrix:", matrix)
print("Elements Greater than 10:", matrix[(matrix > 10)])
print("Elements less than 5 and greater than 15:", matrix[(matrix < 5) & (matrix > 15)])
matrix_copy = matrix.copy()
matrix_copy[matrix_copy < 10] = 0
print("Replace Elements less than 10 with 0:", matrix_copy)
print("\n")



# Q3. Given:
#     arr = np.array([100, 200, 300, 400, 500])

# Use boolean indexing to:
# Print elements divisible by 100
# Print elements not equal to 300

arr = np.array([100, 200, 300, 400, 500])
print("Original Array:", arr)
print("Elements Divisible by 100:", arr[(arr % 100 == 0)])
print("Elements Not Equal to 300:", arr[(arr != 300)])



Original Array: [ 5 10 15 20 25 30]
Elements Greater than 18: [20 25 30]
Even Elements: [10 20 30]
Elements Between 10 and 25: [10 15 20 25]


Original Matrix: [[ 1 12  7]
 [15  3  8]
 [ 9 20  5]]
Elements Greater than 10: [12 15 20]
Elements less than 5 and greater than 15: []
Replace Elements less than 10 with 0: [[ 0 12  0]
 [15  0  0]
 [ 0 20  0]]


Original Array: [100 200 300 400 500]
Elements Divisible by 100: [100 200 300 400 500]
Elements Not Equal to 300: [100 200 400 500]


In [ ]:
# Fancy Indexing: Fancy indexing lets you access multiple array elements at once using lists or arrays of indices. It’s a powerful way to select arbitrary elements in any order, or even repeat elements.


# How it works:

# Instead of slicing, you provide arrays or lists of indices.
# Can be applied to 1D or multi-dimensional arrays.
# Returns a new array containing elements at the specified indices.


#Example 1: 1D Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])

indices = [1, 3, 4]
print("1D Fancy Indexing:", arr[indices])


#Example 2: 2D Fancy Indexing
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = [0, 2]
col_indices = [1, 0]

print("2D Fancy Indexing:", matrix[row_indices, col_indices])


#Fancy Indexing vs Boolean Indexing:

# Fancy indexing uses explicit integer indices.
# Boolean indexing uses boolean masks (True/False).

1D Fancy Indexing: [20 40 50]
2D Fancy Indexing: [2 7]


In [ ]:
#Practice Exercises:

# Q1. Create an array arr = np.array([5, 10, 15, 20, 25, 30]).

#Use fancy indexing to select elements at positions 0, 2, and 4.
arr = np.array([5, 10, 15, 20, 25, 30])
print("Original Array:", arr)
result = arr[[0, 2, 4]]
print("Selected Elements:", result)
print("\n")


# Q2. Given: matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#     Use fancy indexing to select the elements at positions (0,0), (1,1), and (2,2) — the diagonal elements.
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Matrix:", matrix)
diagonal = matrix[[0, 1, 2], [0, 1, 2]]
print("Diagonal Elements:", diagonal)
print("\n")



# Q3. Create an array arr = np.array([10, 20, 30, 40, 50]).
#     Use fancy indexing to select elements in reverse order.
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)
reverse = arr[::-1]
print("Reverse Elements:", reverse)

Original Array: [ 5 10 15 20 25 30]
Selected Elements: [ 5 15 25]


Original Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal Elements: [1 5 9]


Original Array: [10 20 30 40 50]
Reverse Elements: [50 40 30 20 10]


In [5]:
#Sorting Arrays in NumPy: NumPy provides powerful tools to sort arrays efficiently.

#1. Basic Sorting with np.sort(): This function returns a sorted copy of an array (does not change original array).

#Example:
arr = np.array([10, 5, 8, 3])
sorted_arr = np.sort(arr)
print("Original:", arr)
print("Sorted:", sorted_arr)
print("\n")


#2. Sorting 2D Arrays: By default, it sorts each row independently.

#Example:
arr2d = np.array([[3, 1, 2],
                  [9, 5, 6]])

# Row-wise sort
print("Sorted along rows:\n", np.sort(arr2d, axis=1))
print("\n")
# Column-wise sort
print("Sorted along columns:\n", np.sort(arr2d, axis=0))
print("\n")

#3. np.argsort() – Indices of Sorted Elements: Returns indices that would sort the array.

#Example:
arr = np.array([40, 10, 30, 20])
indices = np.argsort(arr)

print("Sorted indices:", indices)
print("Sorted values:", arr[indices])
print("\n")


#4. Sorting in Descending Order: NumPy doesn’t have a direct descending=True flag. We can reverse a sorted array manually:

#Example:
arr = np.array([5, 1, 9])
sorted_desc = np.sort(arr)[::-1]
print("Sorted in Descending Order:", sorted_desc)


Original: [10  5  8  3]
Sorted: [ 3  5  8 10]


Sorted along rows:
 [[1 2 3]
 [5 6 9]]


Sorted along columns:
 [[3 1 2]
 [9 5 6]]


Sorted indices: [1 3 2 0]
Sorted values: [10 20 30 40]


Sorted in Descending Order: [9 5 1]


In [14]:
#Practice Exercises

# #Q1. Create a 1D array with the values: [25, 5, 15, 10, 20]

# Sort the array in ascending order.
# Sort it in descending order.
array_1d = np.array([25, 5, 15, 10, 20])
print("Original Array:", array_1d)
print("Sorted in Ascending Order:", np.sort(array_1d))
print("Sorted in Descending Order:", np.sort(array_1d)[::-1])
print("\n")


# Q2. Create a 2D array:
#       [[12, 45, 78],
#       [34, 23, 67],
#       [89, 11, 50]]

# Sort each row individually.
# Sort each column individually.
array_2d = np.array([[12, 45, 78], [34, 23, 67], [89, 11, 50]])
print("Original Array:", array_2d)
print("Sorted along rows:", np.sort(array_2d, axis=1))
print("Sorted along columns:", np.sort(array_2d, axis=0))
print("\n")


# Q3. Given a 1D array arr = np.array([100, 70, 50, 90]):

# Find the indices that would sort the array.
# Use those indices to sort the array.
arr = np.array([100, 70, 50, 90])
print("Original Array:", arr)
indices = np.argsort(arr)
print("Sorted Indices:", indices)
print("Sorted Array:", arr[indices])
print("\n")



# Q4. Create a 1D array of random integers between 1 and 100 (size = 6).

# Print the array.
# Sort it in descending order using slicing.
arr = np.random.randint(1, 101, size = 6)
print("Original Array:", arr)
print("Sorted in Descending Order:", np.sort(arr)[::-1])



Original Array: [25  5 15 10 20]
Sorted in Ascending Order: [ 5 10 15 20 25]
Sorted in Descending Order: [25 20 15 10  5]


Original Array: [[12 45 78]
 [34 23 67]
 [89 11 50]]
Sorted along rows: [[12 45 78]
 [23 34 67]
 [11 50 89]]
Sorted along columns: [[12 11 50]
 [34 23 67]
 [89 45 78]]


Original Array: [100  70  50  90]
Sorted Indices: [2 1 3 0]
Sorted Array: [ 50  70  90 100]


Original Array: [ 11  74  36   2 100  72]
Sorted in Descending Order: [100  74  72  36  11   2]


In [32]:
#Set Operations in NumPy: NumPy provides several functions to perform set operations on 1D arrays
                          #(usually of numbers or strings), similar to set operations in mathematics.


#1. np.unique(): Returns the sorted unique elements of an array.

arr = np.array([1, 2, 2, 3, 4, 4, 5])
print("Original Array:", arr)
print("Unique Elements:", np.unique(arr))
print("\n")


#2. np.intersect1d(): Returns the common elements of two arrays.

a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print("Array1:", a)
print("Array2:", b)
print("Common Elements:", np.intersect1d(a, b))
print("\n")


#3. np.union1d(): Returns the union (all unique elements) from both arrays.

print("Array1:", a)
print("Array2:", b)
print("Union:", np.union1d(a, b))
print("\n")


#4. np.setdiff1d(): Returns the elements in one array but not in the other.

print("Array1:", a)
print("Array2:", b)
print(np.setdiff1d(a, b))
print(np.setdiff1d(b, a))
print("\n")


#5. np.setxor1d(): Returns elements that are in either of the arrays but not in both (symmetric difference).

print("Array1:", a)
print("Array2:", b)
print("Symmetric Difference:", np.setxor1d(a, b))

Original Array: [1 2 2 3 4 4 5]
Unique Elements: [1 2 3 4 5]


Array1: [1 2 3 4]
Array2: [3 4 5 6]
Common Elements: [3 4]


Array1: [1 2 3 4]
Array2: [3 4 5 6]
Union: [1 2 3 4 5 6]


Array1: [1 2 3 4]
Array2: [3 4 5 6]
[1 2]
[5 6]


Array1: [1 2 3 4]
Array2: [3 4 5 6]
Symmetric Difference: [1 2 5 6]


In [42]:
#Practoce Exercise

# Q1. Given an array:

# arr = np.array([5, 2, 5, 3, 2, 1, 4])
# Find and print all unique elements from the array.
arr = np.array([5, 2, 5, 3, 2, 1, 4])
print("Original Array:", arr)
print("Unique Elements:", np.unique(arr))
print("\n")


# #Q2. Given:
# a = np.array([1, 2, 3, 4])
# b = np.array([3, 4, 5, 6])
# Find elements that are common to both arrays.
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print("Array1:", a)
print("Array2:", b)
print("Common Elements:", np.intersect1d(a, b))
print("\n")


#Q3. Find the union of both arrays a and b.
print("Array1:", a)
print("Array2:", b)
print("Union of a and b:", np.union1d(a, b))
print("\n")


#Q4. Given:
# a = np.array([10, 20, 30, 40])
# b = np.array([30, 40, 50, 60])

# Find:
# Elements in a but not in b.
# Elements in b but not in a.
a = np.array([10, 20, 30, 40])
b = np.array([30, 40, 50, 60])
print("Array1:", a)
print("Array2:", b)
print("Element in a but not in b:", np.setdiff1d(a, b))
print("Element in b but not in a:", np.setdiff1d(b, a))
print("\n")


# Q5. Symmetric Difference
# Using the same a and b:
# Find the elements that are in either a or b, but not both.
print("Array1:", a)
print("Array2:", b)
print("Symmetric Difference:", np.setxor1d(a, b))


Original Array: [5 2 5 3 2 1 4]
Unique Elements: [1 2 3 4 5]


Array1: [1 2 3 4]
Array2: [3 4 5 6]
Common Elements: [3 4]


Array1: [1 2 3 4]
Array2: [3 4 5 6]
Union of a and b: [1 2 3 4 5 6]


Array1: [10 20 30 40]
Array2: [30 40 50 60]
Element in a but not in b: [10 20]
Element in b but not in a: [50 60]


Array1: [10 20 30 40]
Array2: [30 40 50 60]
Symmetric Difference: [10 20 50 60]
