<a href="https://colab.research.google.com/github/rohitjaiswalrj32/Python_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing Numpy Library

import numpy as np

#Example:

# Create a simple array
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


In [ ]:
# Diffrence Between List and Numpy Array:

# | Feature                | Python List                 | NumPy Array                                 |
# | ---------------------- | --------------------------- | ------------------------------------------- |
# |   Data Type            | Can store mixed data types  | Homogeneous (same data type)                |
# |   Performance          | Slower for large operations | Much faster (uses C under the hood)         |
# |   Functionality        | Limited built-in operations | Rich mathematical functions                 |
# |   Memory Consumption   | More                        | Less (compact, fixed type)                  |
# |   Broadcasting         | Not supported               | Supported (auto operations on all elements) |


In [3]:
#1. Creating a List vs NumPy Array

# Python List
py_list = [1, 2, 3, 4]
print(py_list)

# NumPy Array
array1 = np.array([1, 2, 3, 4])
print(array1)

[1, 2, 3, 4]
[1 2 3 4]


In [ ]:
#2. Element-wise Addition

# Python List
py_result = [x + 2 for x in py_list]
print("Python List:", py_result)

# NumPy Array
np_result = np_array + 2
print("NumPy Array:", np_result)


Python List: [3, 4, 5, 6]
NumPy Array: [3 4 5 6]


In [ ]:
#3. Performance Test

import time

# Large list
py_list = list(range(1000000))
np_array = np.array(py_list)

# Time taken by Python list
start = time.time()
py_result = [x * 2 for x in py_list]
print("List Time:", time.time() - start)

# Time taken by NumPy
start = time.time()
np_result = np_array * 2
print("NumPy Time:", time.time() - start)


# Note:

# NumPy arrays are faster, more memory-efficient, and provide advanced math capabilities.
# For data analysis, NumPy arrays are preferred over Python lists.

List Time: 0.05240464210510254
NumPy Time: 0.003787994384765625


In [ ]:
#NumPy Array Creation Techniques

#1. Creating from a Python List or Tuple

# From list
arr1 = np.array([1, 2, 3, 4])
print("From list:", arr1)

# From tuple
arr2 = np.array((5, 6, 7, 8))
print("From tuple:", arr2)

From list: [1 2 3 4]
From tuple: [5 6 7 8]


In [6]:
#2. Creating Arrays of Zeros, Ones, or a Specific Value

# Array of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# Array of ones
ones = np.ones((3, 3))
print("Ones:\n", ones)

# Array filled with a specific value
full = np.full((2, 4), 7)
print("Full:\n", full)

Zeros: [0. 0. 0. 0. 0.]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7 7 7]
 [7 7 7 7]]


In [7]:
#3. Similar to Python's range()

arr_range = np.arange(0, 10, 2)  # start=0, stop=10, step=2
print("Arange:", arr_range)


Arange: [0 2 4 6 8]


In [ ]:
#4. Creating Arrays with Linearly Spaced Values


#Numbers evenly spaced between 0 and 1
arr_linspace = np.linspace(0, 1, 5)
print("Linspace:", arr_linspace)

Linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#5. Creating Identity Matrices

identity = np.eye(4)
print("Identity Matrix:\n", identity)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#6. Creating Random Arrays

# Random floats between 0 and 1
rand_float = np.random.rand(3, 3)
print("Random Float Array:\n", rand_float)

# Random integers between 0 and 10
rand_int = np.random.randint(0, 10, 5)
print("Random Int Array:", rand_int)

Random Float Array:
 [[0.18591125 0.89189206 0.81523071]
 [0.69115558 0.55963777 0.90791623]
 [0.59113133 0.45833362 0.72425332]]
Random Int Array: [8 5 6 4 5]


In [ ]:
# Practice Exercise:

# Q1. An array of ten zeros
zero_array = np.zeros(10)
print("Array of Zeros:", zero_array)

# Q2. A 2x5 array filled with the number 9
array_of_9 = np.full((2,5), 9)
print("Array of 9s:\n", array_of_9)

# Q3. A range array from 10 to 50 with step size 5
range_array = np.arange(10, 51, 5)
print("Range Array:", range_array)

# Q4. An identity matrix of size 3
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# Q5. A 4x4 random float array
random_float = np.random.rand(4, 4)
print("Random floating Array: \n", random_float)

Array of Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 9s:
 [[9 9 9 9 9]
 [9 9 9 9 9]]
Range Array: [10 15 20 25 30 35 40 45 50]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random floating Array: 
 [[0.5867816  0.29525158 0.09468497 0.85276003]
 [0.02527935 0.05153823 0.34823763 0.89132016]
 [0.96481167 0.8717455  0.03964411 0.97799263]
 [0.19430486 0.7463116  0.43448429 0.57075149]]


In [27]:
#NumPy Array Attributes & Properties:#Every NumPy array has several useful attributes
                                     #that tell you about its structure and data type.

#1. shape: Returns a tuple of the array dimensions.

arr = np.array([[1,2,3], [4,5,6]])
print("Array Shape is:", arr.shape)
print(arr)


#2. size: Total number of elements in the array.

arr = np.array([[1,2,3],
               [4,5,6]])
print("Array Size is:", arr.size)
print(arr)


#3. ndim: Number of array dimensions (axes).
arr = np.array([[
                 [1,2,3],
                 [4,5,6],
                 [7,8,9]
              ]])
print("Array Dimension is:", arr.ndim)
print(arr)


#4. dtype: Data type of elements in the array.
arr = np.array([[["Rohit", "Pratik", "Sagar"],
                 [1,2,3],
                 [1.23, 2.34, 3.45]]])
print("Array Data Type is:", arr.dtype)
print(arr)

#5. itemsize: Size (in bytes) of each element.
print("Item Size is:", arr.itemsize)

#6. data: This shows memory location, usually less used directly.
print("Memory Location is:", arr.data)


Array Shape is: (2, 3)
[[1 2 3]
 [4 5 6]]
Array Size is: 6
[[1 2 3]
 [4 5 6]]
Array Dimension is: 3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Array Data Type is: <U32
[[['Rohit' 'Pratik' 'Sagar']
  ['1' '2' '3']
  ['1.23' '2.34' '3.45']]]
Item Size is: 128
Memory Location is: <memory at 0x7897950a96c0>


In [53]:
#Practice Exercise:

# Q1. Create arrays of different shapes and data types, then print and interpret their attributes.
array1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Array Shape is:", array1.shape)
print("Array Size is:", array1.size)
print("Array Dimension is:", array1.ndim)
print("Array Datatype is:", array1.dtype)
print("Array Item Size is:", array1.itemsize)
print("Array Location is:", array1.data)
print("\n")


# Q2. Try changing the dtype when creating an array, e.g., np.array([1, 2, 3], dtype=float) and check the difference.
array2 = np.array([1, 2, 3], dtype=float)
print("Array Datatype is:", array2.dtype)
print("\n")

# Q3. Create a 3x2x2 array and print all its attributes
array3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(array3)
print("Shape:", array3.shape)
print("Size:", array3.size)
print("Dimensions:", array3.ndim)
print("Datatype:", array3.dtype)
print("Item Size (bytes):", array3.itemsize)
print("\n")

# Q4. Create a float array: [5.5, 6.6, 7.7]
array_float = np.array([5.5, 6.6, 7.7])
print("Float Array:", array_float)
print("\n")

# Q5. Print shape, size, dimensions, dtype, and itemsize
print("Array Shape:", array3.shape)
print("Array Size:", array3.size)
print("Array Dimension:", array3.ndim)
print("Array Data Type:", array3.dtype)
print("Array Item Size:", array3.itemsize)
print("\n")

# Q6. Create two arrays: one with int, one with float
array_int = np.array([1, 2, 3])
array_float = np.array([1.1, 2.2, 3.3])
print("Integer Array:", array_int)
print("Float Array:", array_float)
print("\n")

# Q7. Compare itemsize and dtype
print("Integer Array Item Size:", array_int.itemsize)
print("Float Array :", array_float.itemsize)
print("\n")
# Q8. Create an array of integers with dtype='int32'
array_int32 = np.array([1, 2, 3], dtype='int32')
print("Integer Array with dtype='int32':", array_int32)
print("\n")

# Q9. Print array and its itemsize
print(array3, "Item Size: ", array3.itemsize)
print("\n")

# Q10. Create a 1D array of 9 elements
array_1d = np.arange(9)
print("1D Array:", array_1d)
print("Size:", array_1d.size)
print("\n")

# Q11. Reshape to 3x3 and print shape, ndim, size
array_3x3 = array_1d.reshape(3, 3)
print("Reshaped 3x3 Array:\n", array_3x3)
print("Shape:", array_3x3.shape)
print("Dimensions:", array_3x3.ndim)


Array Shape is: (2, 5)
Array Size is: 10
Array Dimension is: 2
Array Datatype is: int64
Array Item Size is: 8
Array Location is: <memory at 0x7897967ccd40>


Array Datatype is: float64


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Shape: (1, 3, 3)
Size: 9
Dimensions: 3
Datatype: int64
Item Size (bytes): 8


Float Array: [5.5 6.6 7.7]


Array Shape: (1, 3, 3)
Array Size: 9
Array Dimension: 3
Array Data Type: int64
Array Item Size: 8


Integer Array: [1 2 3]
Float Array: [1.1 2.2 3.3]


Integer Array Item Size: 8
Float Array : 8


Integer Array with dtype='int32': [1 2 3]


[[[1 2 3]
  [4 5 6]
  [7 8 9]]] Item Size:  8


1D Array: [0 1 2 3 4 5 6 7 8]
Size: 9


Reshaped 3x3 Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape: (3, 3)
Dimensions: 2


In [58]:
# Array Indexing and Slicing: Indexing and slicing in NumPy is similar to Python lists
                              #but offers more powerful and multi-dimensional capabilities.


#1. Basic Indexing: Accessing elements by index
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[-1])
print("\n")


#2. 2D Indexing: Access elements in rows and columns
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr[0, 1])
print(arr[1][2])
print("\n")


#3. Slicing 1D Arrays
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[:3])
print(arr[::2])
print("\n")


#4. Slicing 2D Arrays
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[0:2, 1:])  # Rows 0–1, columns 1–2
print("\n")

10
40


2
6


[20 30 40]
[10 20 30]
[10 30 50]


[[2 3]
 [5 6]]




In [63]:
#Practice Exercise:

# Q1. Create a 1D array of numbers from 0 to 9 and:

# -Print first 5 elements
# -Print last 3 elements
# -Print every second element

arr = np.arange(10)

print("First 5:", arr[:5])
print("Last 3:", arr[-3:])
print("Every 2nd:", arr[::2])
print("\n")

# Q2. Create a 2D array:

# [[10, 20, 30],
#  [40, 50, 60],
#  [70, 80, 90]]

# -Access element 50 using indexing
# -Slice second and third columns
# -Slice first two rows

arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

print("Element at (1,1):", arr2d[1, 1])
print("Second & Third Columns:\n", arr2d[:, 1:])
print("First Two Rows:\n", arr2d[:2, :])
print("\n")


# Q3. Create a 3x3 array and:

# -Print the diagonal elements
# -Print the reverse of the second row

arr3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("Diagonal:", np.diag(arr3))
print("Reversed 2nd row:", arr3[1, ::-1])


First 5: [0 1 2 3 4]
Last 3: [7 8 9]
Every 2nd: [0 2 4 6 8]


Element at (1,1): 50
Second & Third Columns:
 [[20 30]
 [50 60]
 [80 90]]
First Two Rows:
 [[10 20 30]
 [40 50 60]]


Diagonal: [1 5 9]
Reversed 2nd row: [6 5 4]
